export const FETCH_FILE_LOADING = 'FETCH_FILE_LOADING';
export const FETCH_FILE_SUCCESS = 'FETCH_FILE_SUCCESS';
export const FETCH_FILE_ERROR = 'FETCH_FILE_ERROR';
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS';
export const UPDATE_FILE_SUCCESS = 'UPDATE_FILE_SUCCESS';
export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
