export const FETCH_COHORT_LOADING = 'FETCH_COHORT_LOADING';
export const FETCH_COHORT_SUCCESS = 'FETCH_COHORT_SUCCESS';
export const FETCH_COHORTS_SUCCESS = 'FETCH_COHORTS_SUCCESS';
export const DELETE_COHORT_SUCCESS = 'DELETE_COHORT_SUCCESS';