export const FETCH_LECTURE_LOADING = 'FETCH_LECTURE_LOADING';
export const FETCH_LECTURE_SUCCESS = 'FETCH_LECTURE_SUCCESS';
export const FETCH_LECTUREDETAIL_SUCCESS = 'FETCH_LECTUREDETAIL_SUCCESS';
export const FETCH_LECTURE_ERROR = 'FETCH_LECTURE_ERROR';
export const ADD_LECTURE_SUCCESS = 'ADD_LECTURE_SUCCESS';
export const UPDATE_LECTURE_SUCCESS = 'UPDATE_LECTURE_SUCCESS';
export const DELETE_LECTURE_SUCCESS = 'DELETE_LECTURE_SUCCESS';
