export const FETCH_LECTURE_LOADING = 'FETCH_LECTURE_LOADING';
export const FETCH_LECTURE_SUCCESS = 'FETCH_LECTURE_SUCCESS';
export const FETCH_LECTURES_SUCCESS = 'FETCH_LECTURES_SUCCESS';
export const DELETE_LECTURE_SUCCESS = 'DELETE_LECTURE_SUCCESS';