export const FETCH_MCQ_LOADING = 'FETCH_MCQ_LOADING';
export const FETCH_MCQ_SUCCESS = 'FETCH_MCQ_SUCCESS';
export const FETCH_MCQS_SUCCESS = 'FETCH_MCQS_SUCCESS';
export const DELETE_MCQ_SUCCESS = 'DELETE_MCQ_SUCCESS';