export const FETCH_LESSON_LOADING = 'FETCH_LESSON_LOADING';
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS';
export const FETCH_LESSON_SUCCESS = 'FETCH_LESSON_SUCCESS';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
