export const FETCH_LESSON_LOADING = 'FETCH_LESSON_LOADING';
export const FETCH_LESSON_SUCCESS = 'FETCH_LESSON_SUCCESS';
export const FETCH_LESSONDETAIL_SUCCESS = 'FETCH_LESSONDETAIL_SUCCESS';
export const FETCH_LESSON_ERROR = 'FETCH_LESSON_ERROR';
export const ADD_LESSON_SUCCESS = 'ADD_LESSON_SUCCESS';
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
