export const FETCH_COURSE_LOADING = 'FETCH_COURSE_LOADING';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const FETCH_COURSEDETAIL_SUCCESS = 'FETCH_COURSEDETAIL_SUCCESS';
export const FETCH_COURSE_ERROR = 'FETCH_COURSE_ERROR';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
