export const FETCH_COURSE_LOADING = 'FETCH_COURSE_LOADING';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
