export const FETCH_TESTCASE_LOADING = 'FETCH_TESTCASE_LOADING';
export const FETCH_TESTCASE_SUCCESS = 'FETCH_TESTCASE_SUCCESS';
export const FETCH_TESTCASES_SUCCESS = 'FETCH_TESTCASES_SUCCESS';
export const DELETE_TESTCASE_SUCCESS = 'DELETE_TESTCASE_SUCCESS';
export const CLEAR_TESTCASE = 'CLEAR_TESTCASE';
export const FETCH_TESTCASE_EV_LOADING = 'FETCH_TESTCASE_EV_LOADING';